name = "fx-embed"
main = "./dist/worker.js"
compatibility_date = "2024-11-14"
send_metrics = false

[vars]
STANDARD_DOMAIN_LIST = "x.the-diddy.party"
HOST_URL = "https://x.the-diddy.party"
API_HOST_LIST = "x.the-diddy.party"
IGNORE_DOMAIN_LIST = ""

[build]
command = "npm run build"
